# Generated by Django 6.1 on 2026-08-16 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('TRIAL', 'Prueba Gratis (14 días)'), ('BASIC', 'Básico'), ('PRO', 'Profesional'), ('PREMIUM', 'Premium')], default='TRIAL', max_length=20)),
                ('activa_hasta', models.DateTimeField(blank=True, null=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
