# Generated by Django 6.1 on 2026-08-16 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legado', '0002_mensaje_embedding_suscripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('boveda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_familiares', to='legado.boveda')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso_familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
