# Generated by Django 6.1 on 2026-08-16 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legado', '0003_accesofamiliar'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('boveda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='legado.boveda')),
            ],
        ),
    ]
